### ISSUE TITLE
BugTrack投稿に失敗

### ISSUE THREAD

**Issue by huatzhi** [logue/pukiwiki_adv#27]
http://i.imgur.com/iProdE1.png 
http://i.imgur.com/jyQ09kL.png 
http://i.imgur.com/HpXDGHA.png 

脚注/注釈が表示されません

**Comment by logue** [comment]
83e18a78e0222f9e5f5ddcc8a0ca71f3cbe909dc
で修正しました

**Comment by huatzhi** [comment]
まだそこに問題?
http://i.imgur.com/oqTZDea.png
http://i.imgur.com/4WbcebS.png

一方で、pukiwiki.logue.beで新しいページを作成することも可能ではありません
http://i.imgur.com/Lum3NsD.png

**Comment by logue** [comment]
修正しました

**Comment by huatzhi** [comment]
再びpukiwiki.logue.beに新しいページを作成することができないれます?
前の画像と同じ状況 -> http://i.imgur.com/Lum3NsD.png
またはそれは私だけでしょうか？

**Comment by logue** [comment]
失礼、resource.phpをアップしていませんでした。これが原因みたいです。
今は修正したので確認ください。
